name: CPI Linter Demo
on: [push, workflow_dispatch]

jobs:
  cpilint:
    runs-on: ubuntu-latest
    name: CPI Linting
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4.1.1
      - name: cpilint
        uses: addnab/docker-run-action@v3
        with:
          image: jcawley5/cpilint
          options: -v ${{ github.workspace }}:/app/cpi/flows
          run: |
            echo "Running Script" |
            /usr/cpilint-1.0.4/bin/cpilint -rules /app/cpi/rules.xml -directory /app/cpi/flows
