            - name: CPILint
  # You may pin to the exact commit or the version.
  # uses: mosteo-actions/docker-run@1e8c2ac951679fbb21485cbb4eed9e39246ad823
  uses: mosteo-actions/docker-run@v1
  with:
    # A dockerhub image
    image: docker push jcawley5/cpilint
    # Extra parameters to pass to `docker run`
    params: -v ${{ github.workspace }}:/app/cpi/flows  
          
          
