name: CPI Validation
on:
  workflow_dispatch:
jobs:
   CPILint:
    uses: mosteo-actions/docker-run@v1
    with:
      image: jcawley5/cpilint
      params: -v ${{ github.workspace }}:/app/cpi/flows  
