on: [push, workflow_dispatch]

jobs:
  cpilint:
    runs-on: ubuntu-latest
    name: CPI Linting
    steps:
      - name: cpilint
        id: cpilint
        uses: mosteo-actions/docker-run@v1
        with:
          image: jcawley5/cpilint
          params: -v ${{ github.workspace }}:/app/cpi/flows  
